# Generated by Django 5.0.6 on 2024-06-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spess',
            name='age',
            field=models.IntegerField(),
        ),
    ]
