# Generated by Django 5.0.6 on 2024-06-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_alter_spess_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=120)),
            ],
        ),
    ]
