# Generated by Django 5.0.6 on 2024-06-29 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='spess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 29, 12, 40, 32, 637906, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spess',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
