# Generated by Django 5.0.6 on 2024-08-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0005_contact_created_at_contact_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
